- hosts: bigips
  gather_facts: False
  remote_user: root
  tasks:
    - block:
      - name: generate ts configuration
        template:
          src: ../conf.d/templates/ts.json.j2
          dest: ../deps/ts.json

      - name: configure bigip telemetry stream with with ts.json
        uri:
          url: https://{{ inventory_hostname }}:443/mgmt/shared/telemetry/declare
          method: POST
          body: "{{ lookup('file', '../deps/ts.json') }}"
          body_format: json
          headers:
            Content-Type: "application/json"
          url_username: admin
          url_password: "{{ admin_password }}"
          validate_certs: no
        register: result
      
      - name: show ts configuration
        debug: "msg={{result.status }}-{{ result.json.message }}"

      delegate_to: localhost