- hosts: bigips
  gather_facts: False
  remote_user: root
  tasks:
    - block:
      - name: generate as3 configuration
        template:
          src: ../conf.d/templates/as3.pool.json.j2
          dest: "../deps/{{item.name}}-as3.pool.json"
        vars:
          healthMonitors: "{{ item.monitors }}"
          members: "{{ item.members }}"
          poolName: "{{ item.name }}"
        with_items: "{{ pools }}"
        loop_control:
          label: "{{ item.name }}"

      - name: configure bigip pool
        uri:
          url: https://{{ inventory_hostname }}:443/mgmt/shared/appsvcs/declare
          method: POST
          body: "{{ lookup('file', '../deps/' + item.name + '-as3.pool.json') }}"
          body_format: json
          headers:
            Content-Type: "application/json"
          url_username: admin
          url_password: "{{ admin_password }}"
          validate_certs: no
        register: result
        with_items: "{{ pools }}"
        loop_control:
          label: "{{ item.name }}"
      
      # - name: show as3 configuration
      #   debug: "msg={{ result }}"
      delegate_to: localhost